#!/bin/busybox sh

set -e

mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo 0 > /proc/sys/kernel/printk

exec setsid sh /do_tests.sh </dev/ttyS0 >/dev/ttyS0 2>&1
