#!/bin/busybox sh

set -xe

busybox mount -t devtmpfs devtmpfs /dev
busybox mount -t tmpfs tmpfs /tmp
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

echo 0 > /proc/sys/kernel/printk

busybox setsid busybox sh /test.sh >/dev/ttyS0 2>&1 </dev/ttyS0
