#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
mount -t proc proc /proc
mount -t sysfs sysfs /sys


if grep show_klog=0 /proc/cmdline > /dev/null; then
	echo 0 > /proc/sys/kernel/printk
fi

if grep run_gui=0 /proc/cmdline > /dev/null; then
	exec setsid sh -c 'exec sh </dev/ttyS0 >/dev/ttyS0 2>&1'
else
	exec setsid sh -c 'exec sh </dev/tty0 >/dev/tty0 2>&1'
fi
